name: frontend
description: Jurbarkas Flutter Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^9.0.1
  dio: ^5.9.0
  envied: ^1.1.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
